server:
  port: 8989
  servlet:
    context-path: /ems
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems_thymeleaf?characterEncoding=UTF-8
    username: root
    password: 123456

  #静态资源映射
  web:
    resources:
      static-locations: classpath:/templates,classpath:/static/

mybatis:
  mapper-locations: classpath:/com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity

